# Generated by Django 3.2.2 on 2023-03-13 16:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('event_day', models.DateField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_send_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LovedOneProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pet_name', models.CharField(max_length=50)),
                ('pronoun', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('love_language', models.CharField(max_length=20)),
                ('personality', models.CharField(max_length=20)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=5)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='main.eventpreference')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.lovedoneprofile')),
            ],
        ),
        migrations.AddField(
            model_name='eventpreference',
            name='loved_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='main.lovedoneprofile'),
        ),
        migrations.AddField(
            model_name='eventpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
