# Generated by Django 3.2.2 on 2023-03-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_message_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpreference',
            name='send_to_me',
            field=models.BooleanField(default=False),
        ),
    ]
