# Generated by Django 3.2.2 on 2023-04-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_smsresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsresponse',
            name='service',
            field=models.CharField(choices=[('twilio', 'twilio'), ('vonage', 'vonage')], default='vonage', max_length=50),
            preserve_default=False,
        ),
    ]
